// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hznyxnacxjiozfjlfscs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6bnl4bmFjeGppb3pmamxmc2NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NTQ4ODQsImV4cCI6MjA3NzAzMDg4NH0.sPpIPn9nz6K05Md4lrFKPqPp3WYDpTd8sxt7zH7Qt34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});